spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/user_db
    username: postgres
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgres
  main:
    banner-mode: off
logging:
  level:
    org.springframework: error
server:
  error:
    include-message: always